//! `tmem tools --schema openai` and `tmem call <tool>` — the same three tools
//! as the MCP server, for a local model that speaks OpenAI-style tool calling
//! rather than MCP.
//!
//! docs/tech-stack.md: "Same logic as the MCP server, different envelope." The
//! logic lives in `crate::mcp`; there is nothing here but argument handling and
//! the read-only connection.

use crate::db;
use crate::mcp;
use crate::output::{EXIT_EMPTY, EXIT_OK};
use crate::paths;
use anyhow::{Context, Result};
use serde_json::Value;
use std::io::Read;

pub fn tools(schema: &str) -> Result<i32> {
    let v = match schema {
        "openai" => mcp::openai_schema()?,
        "mcp" => mcp::mcp_schema()?,
        other => anyhow::bail!("unknown schema '{other}'; try `openai` or `mcp`"),
    };
    println!("{}", serde_json::to_string_pretty(&v)?);
    Ok(EXIT_OK)
}

pub fn call(tool: &str, args: Option<&str>) -> Result<i32> {
    // `--args -` reads stdin, because a tool call generated by a model is
    // frequently larger and more quote-hostile than a shell argument wants to
    // be.
    let raw = match args {
        None => "{}".to_string(),
        Some("-") => {
            let mut s = String::new();
            std::io::stdin()
                .read_to_string(&mut s)
                .context("reading arguments on stdin")?;
            s
        }
        Some(s) => s.to_string(),
    };
    let parsed: Value = if raw.trim().is_empty() {
        Value::Object(Default::default())
    } else {
        serde_json::from_str(&raw).context("parsing --args as JSON")?
    };

    // Read-only, like the MCP server: `call` is the same surface reached
    // without a protocol, so it gets the same handle and the same guarantee.
    let conn = db::open_readonly(&paths::db_path()?)?;
    let result = mcp::dispatch(&conn, tool, &parsed)?;
    println!("{}", serde_json::to_string_pretty(&result)?);

    // docs/cli.md's exit codes, which a caller wrapping this in a shell
    // function will use: the JSON is printed either way, but `0` means found.
    Ok(if result["count"].as_u64().unwrap_or(0) == 0 {
        EXIT_EMPTY
    } else {
        EXIT_OK
    })
}
